travis:
  secure:
    BINSTAR_TOKEN: DudvKNUOR/cBfgUrJRTvjaOWwZLXVY/4ztu+fdXFbLwVNmxBax59k/nZWgsEazv6/sM0PgvSMCZXHKuRHogxGNFB6XmBDZN/aw41dVkHNHf2PIzOYGOgSIk09XiRU98PpQ8HIg8MAwFO7tnLkafoq7FQnlBQ0rox+r8Ozuiq1M8TaDtx/eOCZS7VoFYfNKQjjIn3C9zIRWb4CZQ2Zn/M0aY91KxShIXjB5v+OY5nclaTFCxbO3Qi7artBxO9hF5BaXmBGTdx9i9PThYhh9QJ+Bf8HQkdpK55fwfyX6fvYRa0lFaTeha4sosRwkZUwEIGOE8ZSwUYXJJO7txyIQcPqt8W5MKGPsKMJe2ks+w5Pll8tRH0GRWJC/irr/41h+a798Cr2KGcvVwotpqWDmnAKz2weZYbq+PVWxczE2/PmlUFjtD+WQkPFgwqQwrRtF9xYrbcpREC46/gjn/SB7zMltBaN2nY+JJRQwS4gJB2yodKYrsDVUoxcTHd7jiM4Ng8YkjLqryGcQk/VupZ+zRuEPXY3mMs7phGraRpQTilGzBmcJyipB2baGfzEqNouGzxtkd7r+OT5kEBOu6ZwRzFl5fYy7tGNW0CaILbMsV6LI2DLWkijs6GvxfRLYtB9C2YzAOxOBKIRH9CX0OOR88ohNruzC+cubJ0cd5hAbwb8yo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
